version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "5500:5500"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
